spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?useSSL=false&serverTimezone=UTC
    username: root
    password: MySqlServer@0721$#
    #driverClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
#      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: update

# In Memory Auth is added , hence commenting the below userdetails
#  security:
#    user:
#      name: kowsalya
#      password: kowsalya123
#      roles: ADMIN

#Logging
logging:
  level:
    org:
      springframework:
        security: DEBUG