spring:
  profiles:
    active: prod

# In Memory Auth is added , hence commenting the below userdetails
#  security:
#    user:
#      name: kowsalya
#      password: kowsalya123
#      roles: ADMIN

#Logging
logging:
  level:
    org:
      springframework:
        security: DEBUG

#JWT Properties
app:
  jwt-secret: JWTSecretKeyValue
  jwt-expiration-milliseconds: 3600000