spring:
  # Swagger 3 throws error - failed to start bean 'documentationpluginsbootstrapper' .
  # Hence add below note
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?useSSL=false&serverTimezone=UTC
    username: root
    password: MySqlServer@0721$#
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
